import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans} from "next/font/google";

const tinos = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={tinos.className}
      >
        {children}
      </body>
    </html>
  );
}
